<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="People.csv" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="People.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Assignment.Interfaces\Assignment.Interfaces.csproj" />
  </ItemGroup>

</Project>
