<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>GenericsHomework_</RootNamespace>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
</Project>
